# Generated by Django 4.2.4 on 2023-08-12 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_category_id_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.category"
            ),
        ),
    ]
